name: Spring Boot CI  # pipline name

on:    # when pipeline will start
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  # work list
  build:
    runs-on: ubuntu-latest  # it will run ubuntu-latest os

    steps:
      - name: Checkout code    # repo clone
        uses: actions/checkout@v3

      - name: Set up JDK 17    # java install
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'   # 

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t springboot-docker-project-app .

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar   #.jar file is uploaded to GitHub as an artifact
